### ISSUE TITLE
About the step 2

### ISSUE THREAD

**Issue by HZHZ66** [rpautrat/SuperPoint#149] opened 2020-05-15 13:38 UTC
Hi
 I am trying to use the server for the second step of training，using GTX 2080Ti gpu. But now I have a problem and cannot run. It is that "W tensorflow/core/framework/op_kernel.cc:1202] OP_REQUIRES failed at cholesky_op.cc:154 : Internal: tensorflow/core/kernels/cuda_solvers.cc:375: cuSolverDN call failed with status =7''.

**Comment by HZHZ66** [comment] 2020-05-15 13:45
![image](https://user-images.githubusercontent.com/62538300/82056863-1dd6ed00-96f5-11ea-825b-f5fbc5df55b0.png)
 
the problem is that, I dont know the reason for the problem. Thanks a lot

**Comment by rpautrat** [comment] 2020-05-15 13:52
Hi,

What are your TF, CUDA and cuDNN versions?

I recently observed this issue for TF 1.7, CUDA 9.0 and cuDNN 7.0. Switching to TF 1.13, CUDA 10.0 and cuDNN 7.5 solved the problem in my case.

**Comment by HZHZ66** [comment] 2020-05-15 14:02
> Hi,
> 
> What are your TF, CUDA and cuDNN versions?
> 
> I recently observed this issue for TF 1.7, CUDA 9.0 and cuDNN 7.0. Switching to TF 1.13, CUDA 10.0 and cuDNN 7.5 solved the problem in my case.
 
Thank you very much for your prompt reply.In my server, tf-gpu-1.6.0, CUDA 9.0, cuDNN 7.0.5. 
I dont know how to solve it.

**Comment by rpautrat** [comment] 2020-05-15 14:10
Yes, so the issue is most likely due to an incompatible version of CUDA and cuDNN. Can you upgrade CUDA and cuDNN on your server?

**Comment by HZHZ66** [comment] 2020-05-15 14:23
> Yes, so the issue is most likely due to an incompatible version of CUDA and cuDNN. Can you upgrade CUDA and cuDNN on your server?

Do you mean I need to upgrade them to version 10.0 and 7.5?
Does TF-1.6  need to be upgraded or downgraded?
thanks a lot.

**Comment by rpautrat** [comment] 2020-05-15 14:27
Yes, upgrading CUDA to 10.0 and cuDNN to 7.5. In that case I think you need to upgrade TF to at least 1.13, because it is the first version for CUDA 10.

**Comment by HZHZ66** [comment] 2020-05-15 14:37
OK,I will have a try. thank you . 谢谢😁

**Comment by HZHZ66** [comment] 2020-05-15 14:51
> Yes, upgrading CUDA to 10.0 and cuDNN to 7.5. In that case I think you need to upgrade TF to at least 1.13, because it is the first version for CUDA 10.

I would like to ask whether the code in this project is applicable to the version you said？thanks.

**Comment by rpautrat** [comment] 2020-05-15 15:08
Yes it should be. I used it recently with the upgraded versions and it ran fine for me.

**Comment by HZHZ66** [comment] 2020-05-17 08:34
> Yes it should be. I used it recently with the upgraded versions and it ran fine for me.
Hi
I ran your demo program and it worked  well.  However, I think the pictures in the HPatches data set are too standard. Normal deep learning is not only good at learning affine transformation caused by perspective differences, but also easy to learn scaling down.  In addition, many of your affine transformation senses are mainly reflected in the difference in horizontal perspective, but in real life affine transformation caused by spatial motion exists both in rotation angle and pitch angle from the spatial perspective.  What will be the matching result if the sample image is replaced by a more complicated picture?

**Comment by HZHZ66** [comment] 2020-05-17 08:35
> Yes it should be. I used it recently with the upgraded versions and it ran fine for me.

Hi
I ran your demo program and it worked well. However, I think the pictures in the HPatches data set are too standard. Normal deep learning is not only good at learning affine transformation caused by perspective differences, but also easy to learn scaling down. In addition, many of your affine transformation senses are mainly reflected in the difference in horizontal perspective, but in real life affine transformation caused by spatial motion exists both in rotation angle and pitch angle from the spatial perspective. What will be the matching result if the sample image is replaced by a more complicated picture?

**Comment by rpautrat** [comment] 2020-05-17 08:42
Well, that's the limitation with homographies: they only model planar moves and cannot model the full diversity of perspective in non planar scenes. Research is currently trying to fix this limitation, for example by training on SfM dataset with ground truth depth (such as [MegaDepth](https://research.cs.cornell.edu/megadepth/)) that allows them to have real perspective changes between two images and still be able to get correspondences between pairs of images.

The current model trained with homographies will still offer decent results on harder images, but performance will slowly degrades when going towards harder perspective transforms.

**Comment by HZHZ66** [comment] 2020-05-17 09:14
> Well, that's the limitation with homographies: they only model planar moves and cannot model the full diversity of perspective in non planar scenes. Research is currently trying to fix this limitation, for example by training on SfM dataset with ground truth depth (such as [MegaDepth](https://research.cs.cornell.edu/megadepth/)) that allows them to have real perspective changes between two images and still be able to get correspondences between pairs of images.
> 
> The current model trained with homographies will still offer decent results on harder images, but performance will slowly degrades when going towards harder perspective transforms.



Ok, thank you for your prompt reply. Rome was not built in a day. I am planning to take the second step of training now, but I want the final training model to be applicable to more complicated visual angle changes.  What adjustments should I make to the parameters in 'magic-point_coco_export.yaml' to achieve my training objectives. Such as scaling_amplitude, perspective_amplitude_x, perspective_amplitude_y? Thank you.
![image](https://user-images.githubusercontent.com/62538300/82140406-762afd80-9861-11ea-9db8-2c921f0aa354.png)

**Comment by rpautrat** [comment] 2020-05-17 09:21
Yes, you can increase the 3 parameters of the config file that you mentioned, plus the parameter `max_angle` to get more rotation invariance. You will have to try different values and visualize them to see how extreme you want your transformations to be. You should also change these parameters in the file `magic-point_coco_train.yaml`.

But note that with more extreme changes, the model will become generally more invariant to changes, but less discriminative. So you will probably observe a drop of performance for 'easy' images with small transformations. The current values have been selected to offer a decent trade-off between discriminativeness and invariance.

**Comment by HZHZ66** [comment] 2020-05-17 09:35
> Yes, you can increase the 3 parameters of the config file that you mentioned, plus the parameter `max_angle` to get more rotation invariance. You will have to try different values and visualize them to see how extreme you want your transformations to be. You should also change these parameters in the file `magic-point_coco_train.yaml`.
> 
> But note that with more extreme changes, the model will become generally more invariant to changes, but less discriminative. So you will probably observe a drop of performance for 'easy' images with small transformations. The current values have been selected to offer a decent trade-off between discriminativeness and invariance.


Thanks a lot. But where is the the parameter 'max_angle'?I cann't find it.

**Comment by rpautrat** [comment] 2020-05-17 09:53
It is currently only in the file `magic-point_coco_train.yaml`. But you can also add it in the file `magic-point_coco_export.yaml`.

**Comment by HZHZ66** [comment] 2020-05-17 10:06
> Yes, you can increase the 3 parameters of the config file that you mentioned, plus the parameter `max_angle` to get more rotation invariance. You will have to try different values and visualize them to see how extreme you want your transformations to be. You should also change these parameters in the file `magic-point_coco_train.yaml`.
> 
> But note that with more extreme changes, the model will become generally more invariant to changes, but less discriminative. So you will probably observe a drop of performance for 'easy' images with small transformations. The current values have been selected to offer a decent trade-off between discriminativeness and invariance.


Thanks.  What should I do to visualize them to see the transformation when I try different values? Could you please tell me ?

**Comment by rpautrat** [comment] 2020-05-17 10:10
You can use the notebook `notebooks/visualize_random_homography.ipynb` and test different parameters here.

**Comment by HZHZ66** [comment] 2020-05-17 10:40
> You can use the notebook `notebooks/visualize_random_homography.ipynb` and test different parameters here.

By the way, if these parameters are raised, will it take longer to train?

**Comment by rpautrat** [comment] 2020-05-17 11:43
No, the training time will be exactly the same.

**Comment by HZHZ66** [comment] 2020-05-17 12:52
> No, the training time will be exactly the same.

Thank you sincerely for your reply. I also want to ask you a question, COCO data set is nearly 20G,Hpatches is 1G. By the time the training is completed, how much capacity  of hard driver will be needed?

**Comment by rpautrat** [comment] 2020-05-17 16:38
You mean how much space does the exported ground truth take on disk? For COCO, it is roughly 90 Mb, so not much.

**Comment by HZHZ66** [comment] 2020-05-17 17:31
Not really.I mean how much space will the whole training take on disk if I finish 7 steps of training.

发自我的iPhone

在 2020年5月18日，上午12:38，Rémi Pautrat <notifications@github.com> 写道：

﻿

You mean how much space does the exported ground truth take on disk? For COCO, it is roughly 90 Mb, so not much.

**Comment by rpautrat** [comment] 2020-05-17 21:25
Well, not much space. The trained models are small (~10 Mb maybe).

The only step that takes a lot of memory is the 7, when you need to export the descriptors on HPatches. It is not well optimized, and it writes all the dense descriptors on disk, which is not very efficient... This can take up to 150 Gb I think. But this is an evaluation step, you don't have necessarily to do it to get a trained model.

**Comment by HZHZ66** [comment] 2020-05-18 11:44
> Well, not much space. The trained models are small (~10 Mb maybe).
> 
> The only step that takes a lot of memory is the 7, when you need to export the descriptors on HPatches. It is not well optimized, and it writes all the dense descriptors on disk, which is not very efficient... This can take up to 150 Gb I think. But this is an evaluation step, you don't have necessarily to do it to get a trained model.


Thanks a lot. I would like to ask you a question, perhaps this question is not very meaningful.  Only train2014 data set was used in the second step. what role did val2014 data set play in the whole training?

**Comment by rpautrat** [comment] 2020-05-18 12:00
val2014 is indeed not used at all during training, and is used for testing only (i.e. step 5).

**Comment by HZHZ66** [comment] 2020-05-18 12:17
> val2014 is indeed not used at all during training, and is used for testing only (i.e. step 5).


Do files in val dataset and train dataset have to correspond one by one?  I want to delete some files from the data set.

**Comment by rpautrat** [comment] 2020-05-18 12:20
They don't correspond at all, it's just different images each time.

Why do you want to delete some images of the dataset exactly?

**Comment by HZHZ66** [comment] 2020-05-18 12:26
> They don't correspond at all, it's just different images each time.
> 
> Why do you want to delete some images of the dataset exactly?


Because the original data set is a little too big for me.  I want to shorten some training time, and my computer hard disk capacity is not very sufficient, it is difficult to complete all the training of the original data set.

**Comment by rpautrat** [comment] 2020-05-18 12:36
I see, it makes sense. Then yes, you can just use one part of the train2014 dataset and everything would work the same.

**Comment by HZHZ66** [comment] 2020-05-19 08:37
> I see, it makes sense. Then yes, you can just use one part of the train2014 dataset and everything would work the same.



Hello, thank you very much for your detailed answer.  I have noticed that your paper compares superpoint algorithm with other traditional CV algorithms and has some graphs.  However, is there any code in this project that compares superpoint with other algorithms?  Introduce some performance evaluation indexes, such as precision, recall.  I want to make a Precision-Recall graph including superpoint and SIFT, ORB.  Thank you.

**Comment by rpautrat** [comment] 2020-05-19 08:56
Hi,

SuperPoint is not my paper, it was originally designed by Daniel DeTone, Tomasz Malisiewicz and Andrew Rabinovich ([https://arxiv.org/abs/1712.07629](https://arxiv.org/abs/1712.07629)). This repo is only a reimplementation of their work.

Currently, only the homography estimation score described in the paper has been implemented for the descriptors evaluation (in `notebooks/descriptors_evaluation_on_hpatches.ipynb`). If you want to evaluate a precision-recall curve for the descriptors matching, you will need to do it by yourself.

Otherwise, there is already a precision-recall curve for the detector only, on the synthetic dataset in `notebooks/detector_evaluation_magic_point.ipynb`. This is only possible on the synthetic because no ground truth is available on real images.

**Comment by HZHZ66** [comment] 2020-05-20 13:33
> Hi,
> 
> SuperPoint is not my paper, it was originally designed by Daniel DeTone, Tomasz Malisiewicz and Andrew Rabinovich (https://arxiv.org/abs/1712.07629). This repo is only a reimplementation of their work.
> 
> Currently, only the homography estimation score described in the paper has been implemented for the descriptors evaluation (in `notebooks/descriptors_evaluation_on_hpatches.ipynb`). If you want to evaluate a precision-recall curve for the descriptors matching, you will need to do it by yourself.
> 
> Otherwise, there is already a precision-recall curve for the detector only, on the synthetic dataset in `notebooks/detector_evaluation_magic_point.ipynb`. This is only possible on the synthetic because no ground truth is available on real images.


Hello. 

I have noticed that other classical detectors can be evaluated in your explanation in the fourth step.
How can I modify the code to do that?  

“python export_detections_repeatability.py  configs/classical-detectors_repeatability.yaml  .........” （How should the following code be modified？）Thank you.

**Comment by rpautrat** [comment] 2020-05-20 14:16
Hi,
If you want to add more baselines than Harris, Shi and FAST, you need to modify the file `models/classical_detectors.py` and add your own detector functions (you can follow the same structure as for the other baselines).
You then just modify the field 'method' of `configs/classical-detectors_repeatability.yaml` with the name of your own method and that's it.

**Comment by HZHZ66** [comment] 2020-05-20 14:28
> Hi,
> If you want to add more baselines than Harris, Shi and FAST, you need to modify the file `models/classical_detectors.py` and add your own detector functions (you can follow the same structure as for the other baselines).
> You then just modify the field 'method' of `configs/classical-detectors_repeatability.yaml` with the name of your own method and that's it.


I see. If I evaluate the Harris in the step 4.  the code “python export_detections_repeatability.py configs/classical-detectors_repeatability.yaml” is enough? The code in the red circle is not used, is it?
![image](https://user-images.githubusercontent.com/62538300/82458327-1e9ec300-9ae9-11ea-8fd5-6beca5902c64.png)

**Comment by rpautrat** [comment] 2020-05-20 15:01
For Harris (or other classical detectors), you can leave 'magic-point_coco' (it won't be used), but you need the export_name parameter, to decide which name you want to give to your exported repeatability.

**Comment by HZHZ66** [comment] 2020-05-21 13:44
> For Harris (or other classical detectors), you can leave 'magic-point_coco' (it won't be used), but you need the export_name parameter, to decide which name you want to give to your exported repeatability.


Hi
When I was running the code for evaluating Harris in step 4,
 " python  export_detections_repeatability.py configs/classical-detectors_repeatability.yaml    Harris   --export_name=Harris_hpatches-repeatability-v". There is an error here.

![捕获5](https://user-images.githubusercontent.com/62538300/82564510-769dfe00-9bab-11ea-9ac6-944ae3078602.JPG)
In the code "classical_detectors.py",the line 10.
![image](https://user-images.githubusercontent.com/62538300/82564816-ff1c9e80-9bab-11ea-9f1a-055795a64ba2.png)
I cannot find "demo_superpoint",where is it?

**Comment by rpautrat** [comment] 2020-05-22 07:36
Hi,
It comes from the repo of the official release of SuperPoint:[https://github.com/magicleap/SuperPointPretrainedNetwork]( https://github.com/magicleap/SuperPointPretrainedNetwork).
You can either clone it and modify the sys.path, or if you don't plan to compare to the official SuperPoint, comment the import line and the few lines of code below that are using it.

**Comment by HZHZ66** [comment] 2020-05-26 03:20
> Hi,
> It comes from the repo of the official release of SuperPoint:https://github.com/magicleap/SuperPointPretrainedNetwork.
> You can either clone it and modify the sys.path, or if you don't plan to compare to the official SuperPoint, comment the import line and the few lines of code below that are using it.


Hi.
In the fifth step of training, I generated the feature detection results of each algorithm as required.  But when I ran Detector _ Repeatability _ Coco.ipynb, this was the result.  The picture cannot be displayed normally.  I don't know why.   I very much hope to get your reply.Thanks a lot.
![image](https://user-images.githubusercontent.com/62538300/82856928-0512d680-9f42-11ea-8c95-0cd8734274a1.png)
![image](https://user-images.githubusercontent.com/62538300/82856965-2c69a380-9f42-11ea-84b0-7355b00da177.png)

**Comment by HZHZ66** [comment] 2020-05-26 03:49
> Hi,
> It comes from the repo of the official release of SuperPoint:https://github.com/magicleap/SuperPointPretrainedNetwork.
> You can either clone it and modify the sys.path, or if you don't plan to compare to the official SuperPoint, comment the import line and the few lines of code below that are using it.


I tried to read the generated ".npz" file.  Here are the results.  I don't know if this seems reasonable.
![image](https://user-images.githubusercontent.com/62538300/82858546-c16e9b80-9f46-11ea-80a6-10ba671e8857.png)
![image](https://user-images.githubusercontent.com/62538300/82858576-d2b7a800-9f46-11ea-86b0-2b92fe7f09d8.png)
![image](https://user-images.githubusercontent.com/62538300/82858605-e82cd200-9f46-11ea-9581-77b92a990676.png)

**Comment by rpautrat** [comment] 2020-05-26 06:47
Hi,
It's because I switched to normalized images between 0 and 1 and some notebooks have not been updated in the meantime and still assume images between 0 and 255. You just need to normalize correctly the images before visualizing them.

**Comment by HZHZ66** [comment] 2020-05-26 08:24
> Hi,
> It's because I switched to normalized images between 0 and 1 and some notebooks have not been updated in the meantime and still assume images between 0 and 255. You just need to normalize correctly the images before visualizing them.


Thank you. Could you please tell me how to normalize correctly the images before visualizing them?
Sorry, my knowledge reserve in this field is not very sufficient.  This is the first time I have carried out a project in the field of deep learning.
![image](https://user-images.githubusercontent.com/62538300/82877859-4ff61380-9f6d-11ea-9c07-588b363d7570.png)

**Comment by HZHZ66** [comment] 2020-05-27 07:57
> Hi,
> It's because I switched to normalized images between 0 and 1 and some notebooks have not been updated in the meantime and still assume images between 0 and 255. You just need to normalize correctly the images before visualizing them.

Without a certain degree of certainty, I dare not make partial changes to the code.

**Comment by rpautrat** [comment] 2020-06-03 20:44
Hi, I have pushed a new version of most visualization that should be compatible with the images normalized between 0 and 1. Let me know if it were not the case.

**Comment by HZHZ66** [comment] 2020-06-07 05:52
> Hi, I have pushed a new version of most visualization that should be compatible with the images normalized between 0 and 1. Let me know if it were not the case.


Hello.  
Thank you very much for updating the project in time. It is very good.  I have a question about the P-R curve in your project. Generally speaking, the curve will not pass through the (1,0) coordinates.  I want to ask why all the curves here pass through (1,0)?
![image](https://user-images.githubusercontent.com/62538300/83961492-253d8080-a8c6-11ea-84f4-325b9869c9ef.png)

**Comment by rpautrat** [comment] 2020-06-07 07:12
Hi, the varying parameter in the PR curves is the number of detected keypoints. In the extreme case when you have a lot of predicted keypoints (let's say in almost every pixels), then you will hit all the ground truth points (hence a recall of 1), but most of your predictions will actually be wrong, so you will get a precision of almost 0 in the limit. Here the precision is actually not exactly 0, but very close to 0.

**Comment by HZHZ66** [comment] 2020-06-07 08:16
> Hi, the varying parameter in the PR curves is the number of detected keypoints. In the extreme case when you have a lot of predicted keypoints (let's say in almost every pixels), then you will hit all the ground truth points (hence a recall of 1), but most of your predictions will actually be wrong, so you will get a precision of almost 0 in the limit. Here the precision is actually not exactly 0, but very close to 0.


I see. Thank you  very much. In addition, I found a small black dot on each curve.  The distribution of these black spots seems to be irregular.  Do these black spots have any practical significance?
![image](https://user-images.githubusercontent.com/62538300/83963648-385a4b80-a8da-11ea-9091-b57a1dbdb961.png)

**Comment by rpautrat** [comment] 2020-06-07 08:55
Those black dots corresponds to the confidence_thresholds set previously that should correspond to the "optimal" number of points in order to get the best trade-off between precision and recall.

![Screenshot from 2020-06-07 10-49-12](https://user-images.githubusercontent.com/32239569/83964387-11395500-a8ad-11ea-9512-c97e9c0f2e52.png)

In your case they are random because you need to manually tune them yourself. So in practice you first display the PR-curves, then manually decide which point on the curve is optimal, try to find to which confidence_thresholds it corresponds to and then plot the black dots to get a confirmation that they are optimal. This might require a trial-and-error until you find the right confidence_thresholds. But once you have this confidence_thresholds for each method, you should fix them and compare all methods with it. That way, you will compare all methods with their best performing confidence_thresholds and get a fair comparison.

**Comment by rpautrat** [comment] 2020-07-03 06:23
I am closing this now, feel free to reopen if you still have questions.

**Closed by rpautrat** 2020-07-03 06:23 UTC

**Comment by HZHZ66** [comment] 2020-10-05 08:35
> I am closing this now, feel free to reopen if you still have questions.

Doctor, please forgive me for my late thank-you speech. I definitely brought you a lot of trouble during my graduation project, because I have asked you many questions, many of which are very basic, and you still patiently give detailed answers. With your help, I graduated from Harbin Institute of Technology smoothly. I hope you can continue to put forward good papers and algorithms in the academic field of computer vision, and I believe you will definitely do this. Finally, I sincerely thank you again and welcome you to visit China, especially Kunming, which has the reputation of spring city, and it is very suitable for visiting all the year round. Besides, I am here, and I can be a tour guide and translator for you, and most importantly, it doesn't cost you any money. I hope we can be friends, my first foreign friend, do you play some social software? Like wechat, Weibo, Twitter and Instagram?

**Comment by rpautrat** [comment] 2020-10-11 13:09
Ah ah, thank you for your kind message :) I just want to help people, and I am happy to hear that my help allowed you to graduate!
I am not using any of these social platforms unfortunately, but you can at least always reach me through my email address: remi.pautrat[at]gmail.com. I have never been to China, but who knows, if that would happen in the future I would be happy to meet you in Kunming, which seems to be a very nice area!

**Comment by HZHZ66** [comment] 2020-10-30 14:33
I am very glad to receive your generous reply. Yes, no one can predict the future. Maybe we will meet one day. The 15th Conference of the Parties to the Convention on Biological Diversity (COP 15) will be held in Kunming next May. When the time comes, you will definitely see the news about the conference in the news media, and you will see the beauty of Kunming and the bright smile of the Chinese people. Wait and see!

发自我的iPhone

在 2020年10月11日，下午9:10，Rémi Pautrat <notifications@github.com> 写道：

﻿

Ah ah, thank you for your kind message :) I just want to help people, and I am happy to hear that my help allowed you to graduate!
I am not using any of these social platforms unfortunately, but you can at least always reach me through my email address: remi.pautrat[at]gmail.com. I have never been to China, but who knows, if that would happen in the future I would be happy to meet you in Kunming, which seems to be a very nice area!

**Comment by rpautrat** [comment] 2020-10-31 22:06
Nice, I'll definitely check the news in May to see that!
